# Generated by Django 6.1 on 2026-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati'), ('hi', 'Hindi')], default='en', max_length=5),
        ),
    ]
