# Generated by Django 6.1 on 2026-08-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='accounts_em_email_451103_idx',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], db_index=True, default='registration', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'purpose', '-created_at'], name='accounts_em_email_1f94e7_idx'),
        ),
        migrations.AddField(
            model_name='loginchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginchallenge',
            index=models.Index(fields=['token'], name='accounts_lo_token_bcd43a_idx'),
        ),
        migrations.AddIndex(
            model_name='loginchallenge',
            index=models.Index(fields=['user', '-created_at'], name='accounts_lo_user_id_f634f0_idx'),
        ),
    ]
