# Generated by Django 6.1 on 2026-08-23 06:24

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=bookings.models.generate_invoice_number, max_length=20, unique=True)),
                ('visit_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_demo', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking')),
            ],
        ),
    ]
