# Generated by Django 6.1 on 2026-08-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('ac', 'AC'), ('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine'), ('geyser', 'Geyser'), ('ro', 'RO Water Purifier'), ('fan', 'Fan'), ('inverter', 'Inverter'), ('laptop', 'Laptop'), ('other', 'Other')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('next_service', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('health_score', models.PositiveSmallIntegerField(default=80)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(max_length=100)),
                ('provider_name', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_replaced', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='maintenance_invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='passport.householdasset')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_diagnosis.aidiagnosis')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
    ]
