# Generated by Django 6.1 on 2026-08-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_gu', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepairGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_gu', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('problem', models.TextField()),
                ('problem_gu', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('estimated_time', models.CharField(max_length=50)),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tools', models.JSONField(default=list)),
                ('materials', models.JSONField(default=list)),
                ('safety_warning', models.TextField(blank=True)),
                ('safety_warning_gu', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('steps_gu', models.JSONField(default=list)),
                ('is_demo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='services.servicecategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('visit_charge_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visit_charge_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('city', models.CharField(default='Ahmedabad', max_length=100)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='services.servicecategory')),
            ],
        ),
    ]
