# Generated by Django 6.1 on 2026-08-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, to='services.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('visit_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('base_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('base_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='providers', to='services.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id', 'Identity'), ('certificate', 'Skill Certificate'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='provider_docs/')),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderBlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='providers.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='providers.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='providers.partnertechnician')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('service_center', 'Authorized Service Center'), ('warranty', 'Warranty Center'), ('spare_parts', 'Spare Parts Seller'), ('repair_company', 'Local Repair Company'), ('home_maintenance', 'Home Maintenance Company'), ('emergency', 'Emergency Service'), ('insurance', 'Insurance Partner'), ('tool_rental', 'Tool Rental'), ('society', 'Society Maintenance')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('authorized_brands', models.JSONField(default=list)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('badges', models.JSONField(default=list)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('response_time_hours', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_available', models.BooleanField(default=False)),
                ('warranty_support', models.BooleanField(default=False)),
                ('spare_parts_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='partners', to='services.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partnertechnician',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='providers.thirdpartypartner'),
        ),
    ]
