# Generated by Django 6.1 on 2026-08-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_partnerquotation_partnersparepart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartypartner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='thirdpartypartner',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
