# Generated by Django 6.1 on 2026-08-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('possible_issue', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('decision', models.CharField(choices=[('Safe DIY', 'Safe DIY'), ('DIY with Caution', 'DIY with Caution'), ('Call Professional', 'Call Professional'), ('Need More Information', 'Need More Information')], default='Need More Information', max_length=30)),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('required_tools', models.JSONField(default=list)),
                ('required_parts', models.JSONField(default=list)),
                ('safety_warning', models.TextField(blank=True)),
                ('instructions', models.JSONField(default=list)),
                ('recommended_provider_category', models.CharField(blank=True, max_length=100)),
                ('input_text', models.TextField(blank=True)),
                ('input_language', models.CharField(default='en', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnosis_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='diagnosis_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='diagnosis_audio/')),
                ('is_dangerous', models.BooleanField(default=False)),
                ('is_demo_mode', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('saved_to_passport', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
